package com.tcs.login.service;

public class UserService {

	public String getUserInfo(){
		
		String userInfo = "<div class='thumbnail'><center><h1>Welcome to the users page</h1></center></div>"
				+ "<table class='table table-striped table-hover table-bordered'>"
				+ "<thead>"
				+ "<tr>"
				+ "<th>Sl No.</th>"
				+ "<th>Employee Id</th>"
				+ "<th>Employee Name</th>"
				+ "<th>Mobile No.</th>"
				+ "</tr>"
				+ "</thead>"
				+ "<tbody>"
				+ "<tr>"
				+ "<td>1</td>"
				+ "<td>763153</td>"
				+ "<td>Tanmay Dey</td>"
				+ "<td>8159090840</td>"
				+ "</tr>"
				+ "<tr>"
				+ "<td>2</td>"
				+ "<td>763154</td>"
				+ "<td>Samz</td>"
				+ "<td>9749266606</td>"
				+ "</tr>"
				+ "<tr>"
				+ "<td>3</td>"
				+ "<td>763153</td>"
				+ "<td>Tanmay Dey</td>"
				+ "<td>8159090840</td>"
				+ "</tr>"
				+ "<tr>"
				+ "<td>4</td>"
				+ "<td>763154</td>"
				+ "<td>Samz</td>"
				+ "<td>9749266606</td>"
				+ "</tr>"
				+ "<tr>"
				+ "<td>5</td>"
				+ "<td>763153</td>"
				+ "<td>Tanmay Dey</td>"
				+ "<td>8159090840</td>"
				+ "</tr>"
				+ "<tr>"
				+ "<td>6</td>"
				+ "<td>763154</td>"
				+ "<td>Samz</td>"
				+ "<td>9749266606</td>"
				+ "</tr>"
				+ "<tr>"
				+ "<td>7</td>"
				+ "<td>763153</td>"
				+ "<td>Tanmay Dey</td>"
				+ "<td>8159090840</td>"
				+ "</tr>"
				+ "<tr>"
				+ "<td>8</td>"
				+ "<td>763154</td>"
				+ "<td>Samz</td>"
				+ "<td>9749266606</td>"
				+ "</tr>"
				+ "<tr>"
				+ "<td>9</td>"
				+ "<td>763153</td>"
				+ "<td>Tanmay Dey</td>"
				+ "<td>8159090840</td>"
				+ "</tr>"
				+ "<tr>"
				+ "<td>10</td>"
				+ "<td>763153</td>"
				+ "<td>Tanmay Dey</td>"
				+ "<td>8159090840</td>"
				+ "</tr>"
				+ "</tbody>"
				+ "</table>";
		
		return userInfo;
	}
}
